version: "3.1"
services:
  app:
    container_name: goms-app
    build:
      context: ../src
      dockerfile: Dockerfile.dev
    env_file:
      - ../.env
    volumes:
      - ../:/workspace 
    networks:
      - goms-network
networks:
  goms-network:
    external: true
    name: "dev-network"
