app:
  name: 'GoMS'
  version: '1.0.0'
  description: 'Go CMS is a simple CMS built with Go'
  environment: 'production'
server:
  host: '0.0.0.0'
  port: 8000
logger:
  level: 1
database:
   default:
    type: 'gorm' 
    driver: 'sqlite3'
    uri: ''
    migration_path: './app/data/database/migrations'
    seed_path: './database/seeds'
storage:
  default: 
    uri: ./storage/app/public
  default_cache:
      uri: ./storage/app/public/.cache
  private:
    uri: ./storage/app/private
  private_cache:
    uri: ./storage/app/private/.cache
  public:
    uri: ./storage/app/public
  public_cache:
    uri: ./storage/app/public/.cache
  tmp:
    uri: ./storage/app/tmp